import type { ResearchSignal } from "@/scoring/signals";
import type { MarketExplanation } from "@/services/explain";
import type { TechnicalOverview } from "@/scoring/technical-stance";

export type ScannerRow = {
  rank: number;
  indexId: number;
  name: string;
  symbol: string;
  category: string;
  current: number;
  change1d: number | null;
  ath: number;
  athDate: string;
  closingAth: number;
  closingAthDate: string;
  intradayAth: number | null;
  distanceFromAth: number;
  drawdownPercent: number;
  bucket: string;
  return1d: number | null;
  return1w: number | null;
  return1m: number | null;
  return3m: number | null;
  return6m: number | null;
  return1y: number | null;
  return2y: number | null;
  return3y: number | null;
  return5y: number | null;
  ma50: number | null;
  ma200: number | null;
  priceVs50: number | null;
  priceVs200: number | null;
  rs1yNifty50: number | null;
  rs1mNifty50: number | null;
  rs3mNifty50: number | null;
  rs6mNifty50: number | null;
  recoveryScore: number;
  opportunityScore: number;
  overallScore: number;
  weaknessScore: number | null;
  classification: string;
  signal: ResearchSignal;
  signalLabel: string;
  trendState: string | null;
  regime: string | null;
  returnType: "PR" | "TR";
  researchNote: string | null;
  explanation: MarketExplanation;
  whyShort: string;
  isBenchmark: boolean;
  technical: TechnicalOverview;
};

export type DashboardSummary = {
  asOf: string | null;
  lastSuccessfulUpdate: string | null;
  dataThrough: string | null;
  stale: boolean;
  provider: string;
  returnType: "PR" | "TR";
  regime: string | null;
  totals: {
    indices: number;
    below30: number;
    below40: number;
    below50: number;
    neg1y: number;
    neg2y: number;
    neg5y: number;
    recoveryCandidates: number;
    fallingKnives: number;
    structural: number;
  };
  lists: {
    beatenDown: ScannerRow[];
    worst1y: ScannerRow[];
    worst2y: ScannerRow[];
    worst5y: ScannerRow[];
    extreme: ScannerRow[];
    recoveries: ScannerRow[];
    fallingKnives: ScannerRow[];
    structural: ScannerRow[];
  };
};
