export type IndexSeed = {
  symbol: string;
  name: string;
  category: string;
  subCategory: string;
  yahooSymbol?: string;
  nseName: string;
  isBenchmark?: boolean;
  description: string;
  inceptionDate?: string;
};

/**
 * Seed universe. Discovery from niftyindices.com can add additional active
 * sectoral/thematic indices without a code change (see providers + seed).
 */
export const INDEX_UNIVERSE: IndexSeed[] = [
  {
    symbol: "NIFTY50",
    name: "Nifty 50",
    nseName: "NIFTY 50",
    yahooSymbol: "^NSEI",
    category: "benchmark",
    subCategory: "broad",
    isBenchmark: true,
    description: "Flagship large-cap benchmark",
    inceptionDate: "1995-04-22",
  },
  {
    symbol: "NIFTY500",
    name: "Nifty 500",
    nseName: "NIFTY 500",
    yahooSymbol: "^CRSLDX",
    category: "benchmark",
    subCategory: "broad",
    isBenchmark: true,
    description: "Broad market benchmark covering ~95% of free-float mcap",
    inceptionDate: "1994-01-01",
  },
  {
    symbol: "NIFTYAUTO",
    name: "Nifty Auto",
    nseName: "NIFTY AUTO",
    yahooSymbol: "^CNXAUTO",
    category: "sectoral",
    subCategory: "auto",
    description: "Automobile manufacturers and ancillaries",
  },
  {
    symbol: "NIFTYBANK",
    name: "Nifty Bank",
    nseName: "NIFTY BANK",
    yahooSymbol: "^NSEBANK",
    category: "sectoral",
    subCategory: "banks",
    description: "Most liquid and large Indian banking stocks",
  },
  {
    symbol: "NIFTYCAPITALGOODS",
    name: "Nifty Capital Goods",
    nseName: "NIFTY CAPITAL GOODS",
    category: "sectoral",
    subCategory: "industrials",
    description: "Capital goods and industrial manufacturing",
  },
  {
    symbol: "NIFTYCEMENT",
    name: "Nifty Cement",
    nseName: "NIFTY CEMENT",
    category: "sectoral",
    subCategory: "materials",
    description: "Cement manufacturers",
  },
  {
    symbol: "NIFTYCHEMICALS",
    name: "Nifty Chemicals",
    nseName: "NIFTY CHEMICALS",
    category: "sectoral",
    subCategory: "materials",
    description: "Specialty and commodity chemical companies",
  },
  {
    symbol: "NIFTYCOMTRANS",
    name: "Nifty Commercial & Transport Services",
    nseName: "NIFTY COMMERCIAL & TRANSPORT SERVICES",
    category: "sectoral",
    subCategory: "services",
    description: "Commercial and transport services",
  },
  {
    symbol: "NIFTYCONSTRUCTION",
    name: "Nifty Construction",
    nseName: "NIFTY CONSTRUCTION",
    category: "sectoral",
    subCategory: "industrials",
    description: "Construction and infrastructure contractors",
  },
  {
    symbol: "NIFTYCONSDUR",
    name: "Nifty Consumer Durables",
    nseName: "NIFTY CONSUMER DURABLES",
    category: "sectoral",
    subCategory: "consumer",
    description: "Consumer durables manufacturers and retailers",
  },
  {
    symbol: "NIFTYCONSSERV",
    name: "Nifty Consumer Services",
    nseName: "NIFTY CONSUMER SERVICES",
    category: "sectoral",
    subCategory: "consumer",
    description: "Consumer services companies",
  },
  {
    symbol: "NIFTYFIN",
    name: "Nifty Financial Services",
    nseName: "NIFTY FINANCIAL SERVICES",
    yahooSymbol: "NIFTY_FIN_SERVICE.NS",
    category: "sectoral",
    subCategory: "financials",
    description: "Banks, NBFCs, insurers and capital-markets firms",
  },
  {
    symbol: "NIFTYFIN2550",
    name: "Nifty Financial Services 25/50",
    nseName: "NIFTY FINANCIAL SERVICES 25/50",
    category: "sectoral",
    subCategory: "financials",
    description: "Financial services with 25/50 capping",
  },
  {
    symbol: "NIFTYFINEXBANK",
    name: "Nifty Financial Services Ex-Bank",
    nseName: "NIFTY FINANCIAL SERVICES EX-BANK",
    category: "sectoral",
    subCategory: "financials",
    description: "Financial services excluding banks",
  },
  {
    symbol: "NIFTYFMCG",
    name: "Nifty FMCG",
    nseName: "NIFTY FMCG",
    yahooSymbol: "^CNXFMCG",
    category: "sectoral",
    subCategory: "consumer",
    description: "Fast-moving consumer goods",
  },
  {
    symbol: "NIFTYHEALTHCARE",
    name: "Nifty Healthcare",
    nseName: "NIFTY HEALTHCARE",
    category: "sectoral",
    subCategory: "healthcare",
    description: "Healthcare providers and related companies",
  },
  {
    symbol: "NIFTYHOSPITALS",
    name: "Nifty Hospitals",
    nseName: "NIFTY HOSPITALS",
    category: "sectoral",
    subCategory: "healthcare",
    description: "Hospital operators",
  },
  {
    symbol: "NIFTYHOUSINGFIN",
    name: "Nifty Housing Finance",
    nseName: "NIFTY HOUSING FINANCE",
    category: "sectoral",
    subCategory: "financials",
    description: "Housing finance companies",
  },
  {
    symbol: "NIFTYINSURANCE",
    name: "Nifty Insurance",
    nseName: "NIFTY INSURANCE",
    category: "sectoral",
    subCategory: "financials",
    description: "Life and general insurers",
  },
  {
    symbol: "NIFTYIT",
    name: "Nifty IT",
    nseName: "NIFTY IT",
    yahooSymbol: "^CNXIT",
    category: "sectoral",
    subCategory: "technology",
    description: "Information technology services and products",
  },
  {
    symbol: "NIFTYMEDIA",
    name: "Nifty Media",
    nseName: "NIFTY MEDIA",
    yahooSymbol: "^CNXMEDIA",
    category: "sectoral",
    subCategory: "communication",
    description: "Media and entertainment",
  },
  {
    symbol: "NIFTYMETAL",
    name: "Nifty Metal",
    nseName: "NIFTY METAL",
    yahooSymbol: "^CNXMETAL",
    category: "sectoral",
    subCategory: "materials",
    description: "Metals and mining",
  },
  {
    symbol: "NIFTYNBFC",
    name: "Nifty NBFC",
    nseName: "NIFTY NBFC",
    category: "sectoral",
    subCategory: "financials",
    description: "Non-bank financial companies",
  },
  {
    symbol: "NIFTYOILGAS",
    name: "Nifty Oil & Gas",
    nseName: "NIFTY OIL & GAS",
    yahooSymbol: "^CNXENERGY",
    category: "sectoral",
    subCategory: "energy",
    description: "Oil, gas and energy companies",
  },
  {
    symbol: "NIFTYPHARMA",
    name: "Nifty Pharma",
    nseName: "NIFTY PHARMA",
    yahooSymbol: "^CNXPHARMA",
    category: "sectoral",
    subCategory: "healthcare",
    description: "Pharmaceutical companies",
  },
  {
    symbol: "NIFTYPOWER",
    name: "Nifty Power",
    nseName: "NIFTY POWER",
    category: "sectoral",
    subCategory: "utilities",
    description: "Power generation and distribution",
  },
  {
    symbol: "NIFTYPVTBANK",
    name: "Nifty Private Bank",
    nseName: "NIFTY PRIVATE BANK",
    yahooSymbol: "NIFTY_PVT_BANK.NS",
    category: "sectoral",
    subCategory: "banks",
    description: "Private sector banks",
  },
  {
    symbol: "NIFTYPSUBANK",
    name: "Nifty PSU Bank",
    nseName: "NIFTY PSU BANK",
    yahooSymbol: "^CNXPSUBANK",
    category: "sectoral",
    subCategory: "banks",
    description: "Public sector banks",
  },
  {
    symbol: "NIFTYREALTY",
    name: "Nifty Realty",
    nseName: "NIFTY REALTY",
    yahooSymbol: "^CNXREALTY",
    category: "sectoral",
    subCategory: "real_estate",
    description: "Real estate developers",
  },
  {
    symbol: "NIFTYREITS",
    name: "Nifty REITs & Realty",
    nseName: "NIFTY REITS & REALTY",
    category: "sectoral",
    subCategory: "real_estate",
    description: "REITs and realty companies",
  },
  {
    symbol: "NIFTYRETAIL",
    name: "Nifty Retail",
    nseName: "NIFTY RETAIL",
    category: "sectoral",
    subCategory: "consumer",
    description: "Retail companies",
  },
  {
    symbol: "NIFTYTELECOM",
    name: "Nifty Telecommunications",
    nseName: "NIFTY TELECOMMUNICATIONS",
    category: "sectoral",
    subCategory: "communication",
    description: "Telecom operators and related firms",
  },
  {
    symbol: "NIFTYMSFIN",
    name: "Nifty MidSmall Financial Services",
    nseName: "NIFTY MIDSMALL FINANCIAL SERVICES",
    category: "sectoral",
    subCategory: "financials",
    description: "Mid and small financial services",
  },
  {
    symbol: "NIFTYMSHEALTH",
    name: "Nifty MidSmall Healthcare",
    nseName: "NIFTY MIDSMALL HEALTHCARE",
    category: "sectoral",
    subCategory: "healthcare",
    description: "Mid and small healthcare",
  },
  {
    symbol: "NIFTYMSITTEL",
    name: "Nifty MidSmall IT & Telecom",
    nseName: "NIFTY MIDSMALL IT & TELECOM",
    category: "sectoral",
    subCategory: "technology",
    description: "Mid and small IT and telecom",
  },
  {
    symbol: "NIFTY500HEALTH",
    name: "Nifty500 Healthcare",
    nseName: "NIFTY500 HEALTHCARE",
    category: "sectoral",
    subCategory: "healthcare",
    description: "Healthcare names within Nifty 500",
  },
];
